server:
  port: 80
  servlet-path: /*
  context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/hz_act?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;useLocalSessionState=true
#    username: root
#    password: root
logging:
  level: info


